#!/bin/bash
# Définition des séquences d'échappement ANSI pour les couleurs
GREEN='\033[0;32m'
NC='\033[0m' # No Color
#ajoute les droit d'execution a tout les utilisateur
chmod -R u+x *
# Demander à l'utilisateur s'il veut ajouter tous les fichiers ou spécifier un fichier
echo "Voulez-vous ajouter tous les fichiers ? (O/n)"
read choice

if [ "$choice" = "n" ] || [ "$choice" = "N" ]; then
	echo "Entrez le nom du fichier à ajouter :"
	read filename
	git add "$filename"
	added_message="$filename a été"
else
	git add .
	added_message="Tous les fichiers ont été"
fi

# Demander à l'utilisateur de saisir le commentaire du commit
echo "Entrez le commentaire de mise à jour du commit :"
read comment

# Effectuer le commit et le push avec le commentaire spécifié
git commit -m "$comment"
git push

# Afficher le message approprié en fonction de ce qui a été ajouté avec la couleur verte
echo -e "${GREEN}$added_message mis à jour sur ton GIT-HUB avec le commentaire \"$comment\"${NC}"